package com.example.myapplication

import android.content.Context
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

val Context.dataStore by preferencesDataStore(name = "app_settings")

enum class Language(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    KANNADA("kn", "ಕನ್ನಡ")
}

object LanguageManager {
    private val LANGUAGE_KEY = stringPreferencesKey("language")

    fun getLanguageFlow(context: Context): Flow<Language> {
        return context.dataStore.data.map { preferences ->
            val languageCode = preferences[LANGUAGE_KEY] ?: Language.ENGLISH.code
            Language.entries.firstOrNull { it.code == languageCode } ?: Language.ENGLISH
        }
    }

    suspend fun setLanguage(context: Context, language: Language) {
        context.dataStore.edit { preferences ->
            preferences[LANGUAGE_KEY] = language.code
        }
    }

    fun getString(context: Context, language: Language, key: String): String {
        return when (language) {
            Language.ENGLISH -> english[key]
            Language.KANNADA -> kannada[key]
        } ?: english[key] ?: key
    }

    private val english = mapOf(
        "app_name" to "Halli Santhe",
        "language_toggle" to "Switch language",
        "welcome" to "Welcome to Halli Santhe Digital",
        "connecting_text" to "Connecting local artisans and farmers directly to your neighborhood.",
        "seller" to "SELLER",
        "seller_subtitle" to "List products & grow business",
        "customer" to "CUSTOMER",
        "customer_subtitle" to "Buy fresh & local goods",
        "already_have_account" to "Already have an account? Login",
        "login" to "Login",
        "privacy" to "PRIVACY",
        "terms" to "TERMS",
        "help" to "HELP",
        "privacy_policy_msg" to "Privacy policy will be added later",
        "terms_msg" to "Terms will be added later",
        "help_center_msg" to "Help center coming soon",
        "halli_santhe" to "Halli Santhe",
        "vendors" to "VENDORS",
        "items_sold" to "ITEMS SOLD",
        "districts" to "DISTRICTS",
        "secure_verification" to "Secure phone verification",
        "enter_phone" to "Enter Your Phone Number",
        "we_send_code" to "We'll send you a verification code",
        "phone_number" to "Phone Number",
        "phone_placeholder" to "00000 00000",
        "send_otp" to "SEND OTP",
        "invalid_phone" to "Enter a valid 10-digit number",
        "joining_as" to "Joining as",
        "terms_agreement" to "By continuing, you agree to Halli Santhe's Terms of Service and Privacy Policy.",
        "help_available_soon" to "Help will be available soon",
        "verification_code" to "Verification Code",
        "enter_6_digit" to "Enter the 6-digit code sent to +91 %s",
        "demo_otp" to "Demo OTP available after sending code",
        "demo_otp_prefix" to "Demo OTP: ",
        "verify_continue" to "VERIFY & CONTINUE",
        "enter_all_6" to "Enter all 6 digits",
        "invalid_otp" to "Invalid OTP",
        "invalid_otp_try_again" to "Invalid OTP. Try again.",
        "resend_code" to "Resend Code",
        "resend_format" to "Resend (%ds)",
        "wrong_number" to "Wrong number? Change Number",
        "encryption_256" to "Secure 256-bit encryption",
        "customer_dashboard" to "Customer Dashboard",
        "browse_products" to "Browse fresh local products",
        "search_products" to "Search products",
        "all" to "All",
        "no_products_found" to "No products found",
        "try_different_search" to "Try a different search or clear the category filters.",
        "vendor_dashboard" to "Vendor Dashboard",
        "welcome_vendor" to "Welcome, ",
        "products" to "Products",
        "reviews" to "Reviews",
        "rating" to "Rating",
        "upload_product" to "Upload Product",
        "view_reviews" to "View Reviews",
        "my_products" to "My Products",
        "no_products_yet" to "No products yet",
        "upload_first_product" to "Upload your first product to start selling.",
        "product_uploaded" to "Product uploaded successfully",
        "upload_product_title" to "Upload Product",
        "tap_to_add_photo" to "Tap to add photo",
        "product_image_required" to "Product image required",
        "selected_photo" to "Selected photo",
        "product_name" to "Product name",
        "product_name_required" to "Product name must be at least 3 characters",
        "price_rupees" to "Price (₹)",
        "valid_price" to "Enter a valid price",
        "origin_source" to "Origin / Source",
        "category" to "Category",
        "select_category" to "Select category",
        "freshness" to "Freshness",
        "freshness_option_1" to "Fresh Today",
        "freshness_option_2" to "1-2 Days Old",
        "freshness_option_3" to "3-5 Days Old",
        "description" to "Description",
        "description_label" to "Description",
        "select_photo" to "Please select a photo",
        "enter_origin" to "Enter origin / source",
        "select_category_msg" to "Select a category",
        "product_detail" to "Product Detail",
        "product_not_found" to "Product not found",
        "chat_whatsapp" to "Chat on WhatsApp",
        "write_review" to "Write a Review",
        "customer_reviews" to "Customer Reviews",
        "no_reviews" to "No reviews yet",
        "sold_out" to "Sold Out",
        "whatsapp_not_installed" to "WhatsApp not installed",
        "product_interested" to "Hi, I'm interested in %s. Is it available?",
        "freshness_label" to "Freshness",
        "origin_label" to "Origin",
        "seller_label" to "Seller",
        "phone_label" to "Phone",
        "no_description" to "No description provided.",
        "based_on_reviews" to "Based on %d reviews",
        "when_customers_rate" to "When customers rate your products, they'll appear here.",
        "write_a_review" to "Write a Review",
        "rating_label" to "Rating: %d / 5",
        "comment" to "Comment",
        "submit" to "Submit",
        "cancel" to "Cancel",
        "review_submitted" to "Review submitted",
        "logout" to "Logout",
        "use_vendor_customer" to "Use Vendor or Customer to continue",
        "could_not_load_image" to "Could not load this image",
        "no_image" to "No image",
        "delete_product" to "Delete Product"
    )

    private val kannada = mapOf(
        "app_name" to "ಹಳ್ಳಿ ಸಂತೆ",
        "language_toggle" to "ಭಾಷೆ ಬದಲಿಸಿ",
        "welcome" to "ಹಳ್ಳಿ ಸಂತೆ ಡಿಜಿಟಲ್‌ಗೆ ಸ್ವಾಗತ",
        "connecting_text" to "ಸ್ಥಳೀಯ ಕಲಾವಿದರು ಮತ್ತು ರೈತರನ್ನು ನೇರವಾಗಿ ನಿಮ್ಮ ನೆರೆಹೊರೆಯವರಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
        "seller" to "ಮಾರಾಟಗಾರ",
        "seller_subtitle" to "ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಿ ಮತ್ತು ವ್ಯಾಪಾರ ಬೆಳೆಸಿರಿ",
        "customer" to "ಗ್ರಾಹಕ",
        "customer_subtitle" to "ತಾಜಾ ಮತ್ತು ಸ್ಥಳೀಯ ವಸ್ತುಗಳನ್ನು ಖರೀದಿಸಿ",
        "already_have_account" to "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್",
        "login" to "ಲಾಗಿನ್",
        "privacy" to "ಗೌಪ್ಯತೆ",
        "terms" to "ನಿಯಮಗಳು",
        "help" to "ಸಹಾಯ",
        "privacy_policy_msg" to "ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ನಂತರ ಸೇರಿಸಲಾಗುತ್ತದೆ",
        "terms_msg" to "ನಿಯಮಗಳನ್ನು ನಂತರ ಸೇರಿಸಲಾಗುತ್ತದೆ",
        "help_center_msg" to "ಸಹಾಯ ಕೇಂದ್ರ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
        "halli_santhe" to "ಹಳ್ಳಿ ಸಂತೆ",
        "vendors" to "ಮಾರಾಟಗಾರರು",
        "items_sold" to "ಮಾರಾಟವಾದ ವಸ್ತುಗಳು",
        "districts" to "ಜಿಲ್ಲೆಗಳು",
        "secure_verification" to "ಸುರಕ್ಷಿತ ಫೋನ್ ಪರಿಶೀಲನೆ",
        "enter_phone" to "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        "we_send_code" to "ನಾವು ನಿಮಗೆ ಪರಿಶೀಲನಾ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ",
        "phone_number" to "ಫೋನ್ ಸಂಖ್ಯೆ",
        "phone_placeholder" to "00000 00000",
        "send_otp" to "OTP ಕಳುಹಿಸಿ",
        "invalid_phone" to "ಸರಿಯಾದ 10 ಅಂಕಿಯ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        "joining_as" to "ನೀವು ಸೇರುತ್ತಿರುವುದು",
        "terms_agreement" to "ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ಹಳ್ಳಿ ಸಂತೆಯ ಸೇವಾ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಒಪ್ಪುತ್ತೀರಿ.",
        "help_available_soon" to "ಸಹಾಯ ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಾಗುತ್ತದೆ",
        "verification_code" to "ಪರಿಶೀಲನಾ ಕೋಡ್",
        "enter_6_digit" to "+91 %s ಗೆ ಕಳುಹಿಸಿದ 6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ",
        "demo_otp" to "ಕೋಡ್ ಕಳುಹಿಸಿದ ನಂತರ ಡೆಮೋ OTP ಲಭ್ಯವಾಗುತ್ತದೆ",
        "demo_otp_prefix" to "ಡೆಮೋ OTP: ",
        "verify_continue" to "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
        "enter_all_6" to "ಎಲ್ಲಾ 6 ಅಂಕಿಗಳನ್ನು ನಮೂದಿಸಿ",
        "invalid_otp" to "ತಪ್ಪಾದ OTP",
        "invalid_otp_try_again" to "ತಪ್ಪಾದ OTP. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        "resend_code" to "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ",
        "resend_format" to "ಮತ್ತೆ ಕಳುಹಿಸಿ (%ds)",
        "wrong_number" to "ತಪ್ಪಾದ ಸಂಖ್ಯೆಯೇ? ಸಂಖ್ಯೆ ಬದಲಿಸಿ",
        "encryption_256" to "ಸುರಕ್ಷಿತ 256-ಬಿಟ್ ಎನ್ಕ್ರಿಪ್ಷನ್",
        "customer_dashboard" to "ಗ್ರಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "browse_products" to "ತಾಜಾ ಸ್ಥಳೀಯ ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ",
        "search_products" to "ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ",
        "all" to "ಎಲ್ಲಾ",
        "no_products_found" to "ಯಾವ ಉತ್ಪನ್ನವೂ ಕಂಡುಬಂದಿಲ್ಲ",
        "try_different_search" to "ಬೇರೆ ಹುಡುಕಾಟ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ವರ್ಗ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ.",
        "vendor_dashboard" to "ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "welcome_vendor" to "ಸ್ವಾಗತ, ",
        "products" to "ಉತ್ಪನ್ನಗಳು",
        "reviews" to "ವಿಮರ್ಶೆಗಳು",
        "rating" to "ರೇಟಿಂಗ್",
        "upload_product" to "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        "view_reviews" to "ವಿಮರ್ಶೆಗಳನ್ನು ನೋಡಿ",
        "my_products" to "ನನ್ನ ಉತ್ಪನ್ನಗಳು",
        "no_products_yet" to "ಇನ್ನೂ ಉತ್ಪನ್ನಗಳಿಲ್ಲ",
        "upload_first_product" to "ಮಾರಾಟ ಆರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ.",
        "product_uploaded" to "ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ",
        "upload_product_title" to "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        "tap_to_add_photo" to "ಫೋಟೋ ಸೇರಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
        "product_image_required" to "ಉತ್ಪನ್ನದ ಚಿತ್ರ ಅಗತ್ಯ",
        "selected_photo" to "ಆಯ್ದ ಫೋಟೋ",
        "product_name" to "ಉತ್ಪನ್ನದ ಹೆಸರು",
        "product_name_required" to "ಉತ್ಪನ್ನದ ಹೆಸರಿನಲ್ಲಿ ಕನಿಷ್ಠ 3 ಅಕ್ಷರಗಳಿರಬೇಕು",
        "price_rupees" to "ಬೆಲೆ (₹)",
        "valid_price" to "ಸರಿಯಾದ ಬೆಲೆಯನ್ನು ನಮೂದಿಸಿ",
        "origin_source" to "ಮೂಲ / ಸ್ಥಳ",
        "category" to "ವರ್ಗ",
        "select_category" to "ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ",
        "freshness" to "ತಾಜಾತನ",
        "freshness_option_1" to "ಇಂದಿನ ತಾಜಾ",
        "freshness_option_2" to "1-2 ದಿನ ಹಳೆಯದು",
        "freshness_option_3" to "3-5 ದಿನ ಹಳೆಯದು",
        "description" to "ವಿವರಣೆ",
        "description_label" to "ವಿವರಣೆ",
        "select_photo" to "ದಯವಿಟ್ಟು ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ",
        "enter_origin" to "ಮೂಲ / ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ",
        "select_category_msg" to "ವರ್ಗ ಆಯ್ಕೆಮಾಡಿ",
        "product_detail" to "ಉತ್ಪನ್ನ ವಿವರ",
        "product_not_found" to "ಉತ್ಪನ್ನ ಕಂಡುಬಂದಿಲ್ಲ",
        "chat_whatsapp" to "WhatsApp ನಲ್ಲಿ ಮಾತನಾಡಿ",
        "write_review" to "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
        "customer_reviews" to "ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು",
        "no_reviews" to "ಇನ್ನೂ ವಿಮರ್ಶೆಗಳಿಲ್ಲ",
        "sold_out" to "ಮಾರಾಟ ಮುಗಿದಿದೆ",
        "whatsapp_not_installed" to "WhatsApp ಸ್ಥಾಪಿಸಲಾಗಿಲ್ಲ",
        "product_interested" to "ನಮಸ್ಕಾರ, ನನಗೆ %s ಬಗ್ಗೆ ಆಸಕ್ತಿ ಇದೆ. ಇದು ಲಭ್ಯವಿದೆಯೇ?",
        "freshness_label" to "ತಾಜಾತನ",
        "origin_label" to "ಮೂಲ",
        "seller_label" to "ಮಾರಾಟಗಾರ",
        "phone_label" to "ಫೋನ್",
        "no_description" to "ವಿವರಣೆ ನೀಡಲಾಗಿಲ್ಲ.",
        "based_on_reviews" to "%d ವಿಮರ್ಶೆಗಳ ಆಧಾರದಲ್ಲಿ",
        "when_customers_rate" to "ಗ್ರಾಹಕರು ನಿಮ್ಮ ಉತ್ಪನ್ನಗಳಿಗೆ ರೇಟಿಂಗ್ ನೀಡಿದಾಗ ಅವು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
        "write_a_review" to "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
        "rating_label" to "ರೇಟಿಂಗ್: %d / 5",
        "comment" to "ಟಿಪ್ಪಣಿ",
        "submit" to "ಸಲ್ಲಿಸಿ",
        "cancel" to "ರದ್ದುಮಾಡಿ",
        "review_submitted" to "ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಲಾಗಿದೆ",
        "logout" to "ಲಾಗ್ ಔಟ್",
        "use_vendor_customer" to "ಮುಂದುವರಿಸಲು ಮಾರಾಟಗಾರ ಅಥವಾ ಗ್ರಾಹಕ ಆಯ್ಕೆಮಾಡಿ",
        "could_not_load_image" to "ಈ ಚಿತ್ರವನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
        "no_image" to "ಚಿತ್ರ ಇಲ್ಲ",
        "delete_product" to "ಉತ್ಪನ್ನ ಅಳಿಸಿ"
    )
}
